# syntax=docker/dockerfile:1.4
FROM nginx:1.27-alpine
RUN rm -rf /usr/share/nginx/html/*

# Nginx config that serves the app under /osm and does SPA fallback
COPY nginx.conf /etc/nginx/conf.d/default.conf

# We'll copy the pre-built Angular files into /usr/share/nginx/html/osm
COPY dist/ /usr/share/nginx/html/osm/

HEALTHCHECK CMD wget -qO- http://localhost/ >/dev/null 2>&1 || exit 1
EXPOSE 80
CMD ["nginx","-g","daemon off;"]
