export enum OliveLotStatus {
  NEW = 'NEW',
  ACCEPTED = 'ACCEPTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REFUSED = 'REFUSED',
  CANCELLED = 'CANCELLED',
  OLIVE_CONTROLLED = 'OLIVE_CONTROLLED',
  OIL_CONTROLLED = 'OIL_CONTROLLED ',
  IN_STOCK = 'IN_STOCK'
}
