export enum OliveLotStatus {
  NEW = 'NEW',
  WAITING_FOR_PRICING = 'WAITING_FOR_PRICING',
  WAITING_FOR_PAYMENT_DETAILS = 'WAITING_FOR_PAYMENT_DETAILS',
  PROD_READY = 'PROD_READY',
  STOCK_READY = 'STOCK_READY',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REFUSED = 'REFUSED',
  CANCELLED = 'CANCELLED',
  OLIVE_CONTROLLED = 'OLIVE_CONTROLLED',
  OIL_CONTROLLED = 'OIL_CONTROLLED',
  IN_STOCK = 'IN_STOCK'
}
