export const ACTION_ICONS: Map<string, string> = new Map<string, string>([
  ['READ', 'visibility'],
  ['DETAIL', 'info'],
  ['CREATE', 'add'],
  ['UPDATE', 'edit'],
  ['DELETE', 'delete'],
  ['CANCEL', 'cancel'],
  ['OLIVE_QUALITY', 'eco'],
  ['OIL_QUALITY', 'opacity'],
  ['UPDATE_OLIVE_QUALITY', 'edit'],
  ['UPDATE_OIL_QUALITY', 'edit'],
  ['TO_PROD', 'rocket_launch'],
  ['COMPLETE', 'check_circle'],
  ['OIL_PAYMENT', 'payment'],
  ['OIL_OUT_TRANSACTION', 'call_made'],
  ['OIL_IN_TRANSACTION', 'call_received'],
  ['OIL_RECEPTION', 'download'],
  ['SET_PRICE', 'attach_money '],
  ['GEN_PDF', 'print'],
  ['GEN_PDF_QC_OIL', 'print'],
  ['GEN_PDF_QC_OLIVE', 'print'],
  ['GEN_PDF_BON_COMMANDE', 'print'],
  ['GEN_INVOICE', 'request_quote'],
  ['GEN_PDF_PRODUCTION', 'build_circle'],
  ['VALIDATE', 'done'],
  ['COMPLETE_PAYMENT_DETAILS', 'attach_money'],
  ['ASSIGN_SUPPLIER', 'assignment_ind'],
  ['PAY', 'payments'],
  ['MAINTENANCE', 'handyman'],
  ['WAITING', 'hourglass_pause'],
  ['RESET_PASSWORD', 'lock_reset']
]);
