// CHANGE: permissions - centralize permission enums and helpers

export enum OSMModule {
  HR = 'HR',
  RECEPTION = 'RECEPTION',
  PRODUCTION = 'PRODUCTION',
  FINANCE = 'FINANCE',
  HABILITATION = 'HABILITATION',
}

export enum HREntity {
  EMPLOYEE = 'EMPLOYEE',
  DEPARTMENT = 'DEPARTMENT',
  CONTRACT = 'CONTRACT',
  LEAVEREQUEST = 'LEAVEREQUEST',
  PAYROLL = 'PAYROLL',
  POINTAGE = 'POINTAGE',
  POSTE = 'POSTE',
}

export enum ReceptionEntity {
  SUPPLIER = 'SUPPLIER',
  SUPPLIERINFO = 'SUPPLIERINFO',
  UNIFIEDDELIVERY = 'UNIFIEDDELIVERY',
}

export enum ProductionEntity {
  QUALITYCONTROLRESULT = 'QUALITYCONTROLRESULT',
  QUALITYCONTROLRULE = 'QUALITYCONTROLRULE',
  STORAGEUNIT = 'STORAGEUNIT',
  MACHINEPLAN = 'MACHINEPLAN',
  MILLMACHINE = 'MILLMACHINE',
  OILTRANSACTION = 'OILTRANSACTION',
  OILCREDIT = 'OILCREDIT',
  base_type = 'base_type',
}

export enum FinanceEntity {
  BANKACCOUNT = 'BANKACCOUNT',
  EXPENSE = 'EXPENSE',
  FINANCIALTRANSACTION = 'FINANCIALTRANSACTION',
  OILSALE = 'OILSALE',
  WASTESALE = 'WASTESALE',
}

export enum HabilitationEntity {
  COMPANYPROFILE = 'COMPANYPROFILE',
  ROLE = 'ROLE',
  PERMISSION = 'PERMISSION',
  OSMUSER = 'OSMUSER',
}

export enum Action {
  READ = 'READ',
  DETAIL = 'DETAIL',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  CANCEL = 'CANCEL',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  VALIDATE = 'VALIDATE',
  PAY = 'PAY',
  GEN_PDF = 'GEN_PDF',
  COMPLETE = 'COMPLETE',
  COMPLETE_PAYMENT_DETAILS = 'COMPLETE_PAYMENT_DETAILS',
  SET_PRICE = 'SET_PRICE',
  ASSIGN_SUPPLIER = 'ASSIGN_SUPPLIER',
  OIL_IN_TRANSACTION = 'OIL_IN_TRANSACTION',
  OIL_OUT_TRANSACTION = 'OIL_OUT_TRANSACTION',
  OIL_PAYMENT = 'OIL_PAYMENT',
  TO_PROD = 'TO_PROD',
  PLANNING = 'PLANNING',
  OLIVE_QUALITY = 'OLIVE_QUALITY',
  OIL_QUALITY = 'OIL_QUALITY',
  UPDATE_OLIVE_QUALITY = 'UPDATE_OLIVE_QUALITY',
  UPDATE_OIL_QUALITY = 'UPDATE_OIL_QUALITY',
  MAINTENANCE = 'MAINTENANCE',
}

export function permissionKey(moduleName: OSMModule, entity: string, action: Action): string {
  return `${moduleName}:${entity}:${action}`;
}


