// CHANGE: permissions - centralize permission enums and helpers
// Entity enums are also generated in permissions.generated.ts (run: node oosm/scripts/sync-permissions.cjs)

export enum OOSMModule {
  HR = 'HR',
  RECEPTION = 'RECEPTION',
  PRODUCTION = 'PRODUCTION',
  FINANCE = 'FINANCE',
  HABILITATION = 'HABILITATION',
  INVENTAIR = 'INVENTAIR',
  CONDITIONING = 'CONDITIONING',
}

export enum HREntity {
  EMPLOYEE = 'EMPLOYEE',
  DEPARTMENT = 'DEPARTMENT',
  CONTRACT = 'CONTRACT',
  LEAVEREQUEST = 'LEAVEREQUEST',
  PAYROLL = 'PAYROLL',
  POINTAGE = 'POINTAGE',
  POSTE = 'POSTE',
}

export enum ReceptionEntity {
  SUPPLIER = 'SUPPLIER',
  SUPPLIERINFO = 'SUPPLIERINFO',
  UNIFIEDDELIVERY = 'UNIFIEDDELIVERY',
}

export enum ProductionEntity {
  QUALITYCONTROLRESULT = 'QUALITYCONTROLRESULT',
  QUALITYCONTROLRULE = 'QUALITYCONTROLRULE',
  STORAGEUNIT = 'STORAGEUNIT',
  MACHINEPLAN = 'MACHINEPLAN',
  MILLMACHINE = 'MILLMACHINE',
  MAINTENANCEWORKORDER = 'MAINTENANCEWORKORDER',
  OILTRANSACTION = 'OILTRANSACTION',
  OILCREDIT = 'OILCREDIT',
  base_type = 'base_type',
  CERTIFICATION='CERTIFICATION'
}

export enum FinanceEntity {
  BANKACCOUNT = 'BANKACCOUNT',
  EXPENSE = 'EXPENSE',
  FINANCIALTRANSACTION = 'FINANCIALTRANSACTION',
  OILSALE = 'OILSALE',
  WASTESALE = 'WASTESALE',
}

export enum HabilitationEntity {
  COMPANYPROFILE = 'COMPANYPROFILE',
  ROLE = 'ROLE',
  PERMISSION = 'PERMISSION',
  OOSMUSER = 'OOSMUSER',
}

export enum InventoryEntity {
  ARTICLESEC = 'ARTICLESEC',
  STOCKSEC = 'STOCKSEC',
  PRODUCT = 'PRODUCT',
  SKU = 'SKU',
  BOM = 'BOM',
  BONCOMMANDE = 'BONCOMMANDE',
  MATERIEL_SUPPLIER = 'MATERIEL_SUPPLIER',
  LIGNECONDITIONNEMENT = 'LIGNECONDITIONNEMENT',
  EMPLACEMENTSTOCK = 'EMPLACEMENTSTOCK',
  MOUVEMENTSTOCKSEC = 'MOUVEMENTSTOCKSEC',
}

export enum ConditioningEntity {
  OF = 'OF',
  PROJET = 'PROJET',
  CLIENT = 'CLIENT',
  CERTIFICATION = 'CERTIFICATION',
  EXPEDITION = 'EXPEDITION',
  QUALITY = 'QUALITY',
  LABELCONTENT = 'LABELCONTENT',
  ANALYTICS = 'ANALYTICS',
  MOBILESYNC = 'MOBILESYNC',
  AUDIT = 'AUDIT',
}

export enum Action {
  READ = 'READ',
  DETAIL = 'DETAIL',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  CANCEL = 'CANCEL',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  VALIDATE = 'VALIDATE',
  PAY = 'PAY',
  GEN_PDF = 'GEN_PDF',
  COMPLETE = 'COMPLETE',
  COMPLETE_PAYMENT_DETAILS = 'COMPLETE_PAYMENT_DETAILS',
  SET_PRICE = 'SET_PRICE',
  ASSIGN_SUPPLIER = 'ASSIGN_SUPPLIER',
  OIL_IN_TRANSACTION = 'OIL_IN_TRANSACTION',
  OIL_OUT_TRANSACTION = 'OIL_OUT_TRANSACTION',
  OIL_PAYMENT = 'OIL_PAYMENT',
  TO_PROD = 'TO_PROD',
  PLANNING = 'PLANNING',
  OLIVE_QUALITY = 'OLIVE_QUALITY',
  OIL_QUALITY = 'OIL_QUALITY',
  UPDATE_OLIVE_QUALITY = 'UPDATE_OLIVE_QUALITY',
  UPDATE_OIL_QUALITY = 'UPDATE_OIL_QUALITY',
  MAINTENANCE = 'MAINTENANCE',
  DELIVERYHISTORY = 'DELIVERYHISTORY',
  GEN_PDF_QC_OIL = 'GEN_PDF_QC_OIL',
  GEN_PDF_QC_OLIVE = 'GEN_PDF_QC_OLIVE',
  GEN_PDF_PRODUCTION = 'GEN_PDF_PRODUCTION',
  START = 'START',
  PAUSE = 'PAUSE',
  RESUME = 'RESUME',
  CLOSE = 'CLOSE',
  SHIP = 'SHIP',
  DELIVER = 'DELIVER',
  ADD_LINE = 'ADD_LINE',
  REMOVE_LINE = 'REMOVE_LINE',
  UPDATE_STATUS = 'UPDATE_STATUS',
  DRAFT = 'DRAFT',
  FINALIZE = 'FINALIZE',
  EXPORT = 'EXPORT',
  SYNC = 'SYNC',
  REPORT = 'REPORT',
  ENTREE_STOCK = 'ENTREE_STOCK',
  SORTIE_STOCK = 'SORTIE_STOCK',
  AJUSTER_STOCK = 'AJUSTER_STOCK',
  ASSIGN_EMPLACEMENT = 'ASSIGN_EMPLACEMENT',
  RESERVER_STOCK = 'RESERVER_STOCK',
  LIBERER_STOCK = 'LIBERER_STOCK',
  CHECK_STOCK = 'CHECK_STOCK',
  TRANSFERER_STOCK = 'TRANSFERER_STOCK',
}

export function permissionKey(moduleName: OOSMModule, entity: string, action: Action): string {
  return `${moduleName}:${entity}:${action}`;
}


